# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: William Kessler, MS
email: willhkessler@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: WillhKessler
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones



include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "William Kessler"
  avatar : "/assets/images/WillK_HS.jpg"
  bio    : "Health Geographer and Geospatial Data Specialist. My interests lie where maps, public health, and the outdoors intersect."
  links:
    - label: "Orcid iD"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/my-orcid?orcid=0000-0003-3574-5400"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/williamhkessler"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WillhKessler"
    - label: "@willhkessler"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/willhkessler"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "www.linkedin.com/in/williamhkessler"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WillhKessler"
    - label: "@willhkessler"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/willhkessler"

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  anothercollection:
    output: true
    permalink: /:collection/:path/
    
  

    
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      collections:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
